### ISSUE TITLE
SLOT_RE not working anymore!

### ISSUE THREAD

**Issue by chanhchuachin** [paradigmxyz/sinker#15]
SLOT_RE need update, it return None all match !!
![image](https://github.com/user-attachments/assets/a511f082-4333-4028-b776-52571ef37920)

**Comment by loren** [comment]
I'm unable to reproduce this behavior. If you are still having a problem with it, please open a new issue with some additional information:

- version of Postgres
- version of Elasticsearch
- your `products` schema, materialized view SQL, and Elasticsearch mapping
- what you're seeing vs what you're expecting
